In [ ]:
import numpy as np

In [ ]:
#
a = np.arange(6).reshape(2,3)
a

In [ ]:
#
b = np.arange(6,12).reshape(2,3)
b

In [6]:
#2x3配列を横に結合
np.hstack([a,b])

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [7]:
#2X3配列を縦に結合
np.vstack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
#
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
#リストのスライス：0, 2, 4行目のみ抽出
a[[0,2,4],:]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [10]:
#リストのスライス：0, 2, 4列目のみ抽出
a[:, [0,2,4]]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [11]:
a[:, [1,3]]

array([[ 1,  3],
       [ 7,  9],
       [13, 15],
       [19, 21],
       [25, 27]])

In [12]:
#条件にあった数値を置き換える
a[a % 2 == 0] = -1
a

array([[-1,  1, -1,  3, -1,  5],
       [-1,  7, -1,  9, -1, 11],
       [-1, 13, -1, 15, -1, 17],
       [-1, 19, -1, 21, -1, 23],
       [-1, 25, -1, 27, -1, 29]])

In [13]:
#配列のコピーはポインタのコピー->コピー先を変えると元も変わる
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
b = a
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b[0,1] = 6
b

array([[0, 6, 2],
       [3, 4, 5]])

In [17]:
a

array([[0, 6, 2],
       [3, 4, 5]])

In [18]:
#実体をコピーするにはcopyを使用
a = np.arange(6).reshape(2,3)
b1 = a.copy()
b2 = np.copy(a)   #どちらも実体のコピー
b1[0,1] = 6
b2[0,1] = 6
a

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
b1

array([[0, 6, 2],
       [3, 4, 5]])