In [1]:
import numpy as np

ImportError: No module named 'numpy'

In [2]:
#大きさ５の配列生成
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
#大きさ10で要素が0-9の配列生成
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#上の省略型
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#2行3列の配列生成
np.array([[0,1,2],[3,4,5]])

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
#配列の形を変える
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
#reshapeの元は一次元でなくてもよい
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
#変更先の配列は３次元以上でもよい
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [17]:
#配列の形を知る
a = np.arange(60).reshape(10,6)
a.shape

(10, 6)

In [18]:
#配列の要素数を知る
a.size

60

In [20]:
#行数と列数を知る
nrow, ncol = a.shape
(nrow, ncol)

(10, 6)

In [21]:
#全要素が実数ゼロの配列生成
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [22]:
#全要素が実数1の配列生成
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [23]:
#単に指定の大きさの配列を生成
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
#標準正規分布から５つの乱数生成
np.random.randn(5)

array([ 0.17104137, -1.03317821,  0.2586098 ,  1.05340306,  1.38733802])

In [29]:
#２項分布
np.random.binomial(n=100, p=0.1, size=(10))

array([14,  7, 11,  6, 10, 10, 10, 10, 13, 12])

In [30]:
#区間(0,1)の一様分布を３個生成
np.random.uniform(0,1,3)

array([ 0.55218067,  0.88241708,  0.24088991])

In [32]:
#平均1.5, 標準偏差2の正規分布に従う３個乱数生成
np.random.normal(1.5, 2.0, 3)

array([ 4.84228134,  1.4174009 ,  1.73346081])

In [33]:
#乱数をシャッフル
np.random.permutation(range(6))

array([0, 3, 1, 5, 2, 4])

In [34]:
#上記の省略形
np.random.permutation(6)

array([5, 3, 2, 1, 4, 0])

In [35]:
#5x5単位行列
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])