In [1]:
import numpy as np

ImportError: No module named 'numpy'

In [3]:
#
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#配列の対する数値演算は要素すべてに適用される(numpyの規則)
a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
#通常パッケージのmathで定義されているものではなくnumpyの関数を使う
np.log(a)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947]])

In [8]:
#全要素の和を計算
np.sum(a)

21

In [9]:
#全要素の平均を計算
np.mean(a)

3.5

In [10]:
#列ごとに行の和を計算
np.sum(a, axis=0)

array([5, 7, 9])

In [11]:
#行ごとに列の和を計算
np.sum(a, axis=1)

array([ 6, 15])

In [12]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
b = np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
#同じサイズの行列の演算は要素ごとに行われる
a + b

array([[ 6,  8, 10],
       [12, 14, 16]])

In [15]:
a * b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [16]:
#整数だが実数の計算結果になる
a / b

array([[ 0.        ,  0.14285714,  0.25      ],
       [ 0.33333333,  0.4       ,  0.45454545]])

In [17]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [18]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [19]:
#配列が一次元のときは内積を計算
a.dot(b)

38

In [21]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
b = np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
#行列の掛け算
a.dot(b)

array([[10, 13],
       [28, 40]])

In [24]:
#2次元行列の掛け算でサイズが適切でない場合
a.dot(a)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [25]:
#逆行列、転置行列、行列式、固有値
a = np.array([[0,6,3],[-2,7,2],[0,3,3]])
a

array([[ 0,  6,  3],
       [-2,  7,  2],
       [ 0,  3,  3]])

In [26]:
#転置行列
a.T

array([[ 0, -2,  0],
       [ 6,  7,  3],
       [ 3,  2,  3]])

In [27]:
#行列式
np.linalg.det(a) #detが0でないので行列式が存在する

17.999999999999996

In [28]:
#逆行列
np.linalg.inv(a)

array([[ 0.83333333, -0.5       , -0.5       ],
       [ 0.33333333,  0.        , -0.33333333],
       [-0.33333333,  0.        ,  0.66666667]])

In [30]:
#固有値と固有ベクトル
la, v = np.linalg.eig(a)
la

array([ 6.,  3.,  1.])

In [31]:
a

array([[ 0,  6,  3],
       [-2,  7,  2],
       [ 0,  3,  3]])

In [32]:
a[::-1]

array([[ 0,  3,  3],
       [-2,  7,  2],
       [ 0,  6,  3]])

In [68]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
word[::2]

['1st', '3rd', '5th']

In [56]:
word[-4:-1]

['2nd', '3rd', '4th']

In [57]:
word[::-1]

['5th', '4th', '3rd', '2nd', '1st']

In [59]:
word[2::2]

['3rd', '5th']