In [1]:
import numpy as np

In [2]:
#pickleを使って配列の保存と呼び出し
a = np.random.randn(10000).reshape(100,100)
a

array([[-0.13224225, -0.86121899, -0.55053511, ...,  0.65351721,
        -1.09470259,  0.73921831],
       [-0.62127678, -0.46555495, -0.30091046, ...,  0.27522449,
        -0.56830495,  0.43987613],
       [-0.12670861,  0.2297186 , -0.31131092, ...,  0.44941722,
         0.21268488, -0.79614182],
       ..., 
       [-0.29148706,  0.93930523, -1.02990819, ...,  0.30482479,
        -0.95298536,  0.0496585 ],
       [ 0.21320874,  0.29580025,  1.01963055, ..., -0.74878423,
         1.39377298, -1.4166485 ],
       [ 0.96450962, -0.80696792,  0.31716551, ...,  3.1184805 ,
         1.63840809, -0.45264727]])

In [10]:
import pickle
f = open('a.pickle', 'wb') #テキストモード'w'にすると実行時エラー
pickle.dump(a,f)
f.close()

In [12]:
f = open('a.pickle', 'rb') #'r'にするとload時にエラー
a = pickle.load(f)
f.close()
a

array([[-0.13224225, -0.86121899, -0.55053511, ...,  0.65351721,
        -1.09470259,  0.73921831],
       [-0.62127678, -0.46555495, -0.30091046, ...,  0.27522449,
        -0.56830495,  0.43987613],
       [-0.12670861,  0.2297186 , -0.31131092, ...,  0.44941722,
         0.21268488, -0.79614182],
       ..., 
       [-0.29148706,  0.93930523, -1.02990819, ...,  0.30482479,
        -0.95298536,  0.0496585 ],
       [ 0.21320874,  0.29580025,  1.01963055, ..., -0.74878423,
         1.39377298, -1.4166485 ],
       [ 0.96450962, -0.80696792,  0.31716551, ...,  3.1184805 ,
         1.63840809, -0.45264727]])

In [13]:
#numpy;配列をバイナリで保存
np.save('a.npy', a)
b = np.load('a.npy')

In [14]:
b

array([[-0.13224225, -0.86121899, -0.55053511, ...,  0.65351721,
        -1.09470259,  0.73921831],
       [-0.62127678, -0.46555495, -0.30091046, ...,  0.27522449,
        -0.56830495,  0.43987613],
       [-0.12670861,  0.2297186 , -0.31131092, ...,  0.44941722,
         0.21268488, -0.79614182],
       ..., 
       [-0.29148706,  0.93930523, -1.02990819, ...,  0.30482479,
        -0.95298536,  0.0496585 ],
       [ 0.21320874,  0.29580025,  1.01963055, ..., -0.74878423,
         1.39377298, -1.4166485 ],
       [ 0.96450962, -0.80696792,  0.31716551, ...,  3.1184805 ,
         1.63840809, -0.45264727]])

In [17]:
#numpy:テキストデータとして保存(savetxt)
np.savetxt('a.data', a)
c = np.loadtxt('a.data')
c

array([[-0.13224225, -0.86121899, -0.55053511, ...,  0.65351721,
        -1.09470259,  0.73921831],
       [-0.62127678, -0.46555495, -0.30091046, ...,  0.27522449,
        -0.56830495,  0.43987613],
       [-0.12670861,  0.2297186 , -0.31131092, ...,  0.44941722,
         0.21268488, -0.79614182],
       ..., 
       [-0.29148706,  0.93930523, -1.02990819, ...,  0.30482479,
        -0.95298536,  0.0496585 ],
       [ 0.21320874,  0.29580025,  1.01963055, ..., -0.74878423,
         1.39377298, -1.4166485 ],
       [ 0.96450962, -0.80696792,  0.31716551, ...,  3.1184805 ,
         1.63840809, -0.45264727]])